spring:
  application:
    name: command-cashflow-service
  cloud:
    gcp:
      project-id: groovy-iris-490717-u0
      credentials:
        # Em produção, ideal é usar ADC (não setar arquivo aqui!!!!).
        # Para desenvolvimento local:
        location: file:../../../../../../.config/gcloud/application_default_credentials.json
      spanner:
        instance-id: my-certification-spanner-01
        database: cashflowoltp
server:
  port: 8080
  servlet:
    context-path: /cashflow