spring:
  application:
    name: command-cashflow-service

  threads:
    virtual:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /cashflow

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics