spring:
  application:
    name: command-cashflow-service
  cloud:
    gcp:
      project-id: test-project
      spanner:
        instance-id: test-instance
        database: test-database
        emulator:
          enabled: true
        emulator-host: localhost:9010
      pubsub:
        emulator-host: localhost:8085
server:
  port: 8080
  servlet:
    context-path: /