spring:
  application:
    name: query-cashflow-service
  cloud:
    gcp:
      project-id: test-project
      credentials:
      # Em produção, ideal é usar ADC (não setar arquivo aqui!!!!).
      spanner:
        instance-id: test-instance
        database: test-database
        emulator:
          enabled: true
        emulator-host: localhost:9010
server:
  port: 8081
  servlet:
    context-path: /cashflow