spring:
  application:
    name: query-cashflow-service
  cloud:
    gcp:
      project-id: groovy-iris-490717-u0
      credentials:
        # Em produção, ideal é usar ADC (não setar arquivo aqui!!!!).
        # Para desenvolvimento local:
        location: file:../../../../../../.config/gcloud/application_default_credentials.json
      spanner:
        instance-id: my-certification-spanner-01
        database: cashflowoltp
        emulator:
          enabled: false
        emulator-host: localhost:9010
server:
  port: 8081
  servlet:
    context-path: /cashflow