spring:
  application:
    name: consolidator-cashflow-service
  cloud:
    gcp:
      project-id: test-project
      credentials:
      # Em produção, ideal é usar ADC (não setar arquivo aqui!!!!).
      spanner:
        instance-id: test-instance
        database: test-database
        emulator:
          enabled: true
        emulator-host: localhost:9010
      pubsub:
        # configs opcionais de subscriber
        subscriber:
          parallel-pull-count: 2
          executor-threads: 4
